#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KhachSan")]
	public partial class dbQLKhachSanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietDichVu(ChiTietDichVu instance);
    partial void UpdateChiTietDichVu(ChiTietDichVu instance);
    partial void DeleteChiTietDichVu(ChiTietDichVu instance);
    partial void InsertChiTietThuePhong(ChiTietThuePhong instance);
    partial void UpdateChiTietThuePhong(ChiTietThuePhong instance);
    partial void DeleteChiTietThuePhong(ChiTietThuePhong instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertDoan(Doan instance);
    partial void UpdateDoan(Doan instance);
    partial void DeleteDoan(Doan instance);
    partial void InsertHoaDonDichVu(HoaDonDichVu instance);
    partial void UpdateHoaDonDichVu(HoaDonDichVu instance);
    partial void DeleteHoaDonDichVu(HoaDonDichVu instance);
    partial void InsertHoaDonTienPhong(HoaDonTienPhong instance);
    partial void UpdateHoaDonTienPhong(HoaDonTienPhong instance);
    partial void DeleteHoaDonTienPhong(HoaDonTienPhong instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiPhong(LoaiPhong instance);
    partial void UpdateLoaiPhong(LoaiPhong instance);
    partial void DeleteLoaiPhong(LoaiPhong instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    partial void InsertThuePhong(ThuePhong instance);
    partial void UpdateThuePhong(ThuePhong instance);
    partial void DeleteThuePhong(ThuePhong instance);
    #endregion
		
		public dbQLKhachSanDataContext() : 
				base(global::DAL.Properties.Settings.Default.KhachSanConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLKhachSanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLKhachSanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLKhachSanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLKhachSanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietDichVu> ChiTietDichVus
		{
			get
			{
				return this.GetTable<ChiTietDichVu>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietThuePhong> ChiTietThuePhongs
		{
			get
			{
				return this.GetTable<ChiTietThuePhong>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<Doan> Doans
		{
			get
			{
				return this.GetTable<Doan>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonDichVu> HoaDonDichVus
		{
			get
			{
				return this.GetTable<HoaDonDichVu>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonTienPhong> HoaDonTienPhongs
		{
			get
			{
				return this.GetTable<HoaDonTienPhong>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiPhong> LoaiPhongs
		{
			get
			{
				return this.GetTable<LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
		
		public System.Data.Linq.Table<ThuePhong> ThuePhongs
		{
			get
			{
				return this.GetTable<ThuePhong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDichVu")]
	public partial class ChiTietDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maThue;
		
		private string _maKhach;
		
		private string _maPhong;
		
		private string _maDV;
		
		private int _soLuong;
		
		private EntityRef<ChiTietThuePhong> _ChiTietThuePhong;
		
		private EntityRef<DichVu> _DichVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaThueChanging(string value);
    partial void OnmaThueChanged();
    partial void OnmaKhachChanging(string value);
    partial void OnmaKhachChanged();
    partial void OnmaPhongChanging(string value);
    partial void OnmaPhongChanged();
    partial void OnmaDVChanging(string value);
    partial void OnmaDVChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    #endregion
		
		public ChiTietDichVu()
		{
			this._ChiTietThuePhong = default(EntityRef<ChiTietThuePhong>);
			this._DichVu = default(EntityRef<DichVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThue", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThue
		{
			get
			{
				return this._maThue;
			}
			set
			{
				if ((this._maThue != value))
				{
					if (this._ChiTietThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaThueChanging(value);
					this.SendPropertyChanging();
					this._maThue = value;
					this.SendPropertyChanged("maThue");
					this.OnmaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhach", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhach
		{
			get
			{
				return this._maKhach;
			}
			set
			{
				if ((this._maKhach != value))
				{
					if (this._ChiTietThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachChanging(value);
					this.SendPropertyChanging();
					this._maKhach = value;
					this.SendPropertyChanged("maKhach");
					this.OnmaKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhong", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhong
		{
			get
			{
				return this._maPhong;
			}
			set
			{
				if ((this._maPhong != value))
				{
					if (this._ChiTietThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongChanging(value);
					this.SendPropertyChanging();
					this._maPhong = value;
					this.SendPropertyChanged("maPhong");
					this.OnmaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDV", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDV
		{
			get
			{
				return this._maDV;
			}
			set
			{
				if ((this._maDV != value))
				{
					if (this._DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDVChanging(value);
					this.SendPropertyChanging();
					this._maDV = value;
					this.SendPropertyChanged("maDV");
					this.OnmaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietThuePhong_ChiTietDichVu", Storage="_ChiTietThuePhong", ThisKey="maThue,maKhach,maPhong", OtherKey="maThue,maKhach,maPhong", IsForeignKey=true)]
		public ChiTietThuePhong ChiTietThuePhong
		{
			get
			{
				return this._ChiTietThuePhong.Entity;
			}
			set
			{
				ChiTietThuePhong previousValue = this._ChiTietThuePhong.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietThuePhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietThuePhong.Entity = null;
						previousValue.ChiTietDichVus.Remove(this);
					}
					this._ChiTietThuePhong.Entity = value;
					if ((value != null))
					{
						value.ChiTietDichVus.Add(this);
						this._maThue = value.maThue;
						this._maKhach = value.maKhach;
						this._maPhong = value.maPhong;
					}
					else
					{
						this._maThue = default(string);
						this._maKhach = default(string);
						this._maPhong = default(string);
					}
					this.SendPropertyChanged("ChiTietThuePhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_ChiTietDichVu", Storage="_DichVu", ThisKey="maDV", OtherKey="maDV", IsForeignKey=true)]
		public DichVu DichVu
		{
			get
			{
				return this._DichVu.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu.Entity;
				if (((previousValue != value) 
							|| (this._DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu.Entity = null;
						previousValue.ChiTietDichVus.Remove(this);
					}
					this._DichVu.Entity = value;
					if ((value != null))
					{
						value.ChiTietDichVus.Add(this);
						this._maDV = value.maDV;
					}
					else
					{
						this._maDV = default(string);
					}
					this.SendPropertyChanged("DichVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietThuePhong")]
	public partial class ChiTietThuePhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maThue;
		
		private string _maKhach;
		
		private string _maPhong;
		
		private System.DateTime _ngayVao;
		
		private System.DateTime _ngayRa;
		
		private System.TimeSpan _gioVao;
		
		private System.TimeSpan _gioRa;
		
		private byte _trangThai;
		
		private System.Nullable<decimal> _tienKhac;
		
		private string _ghiChu;
		
		private EntitySet<ChiTietDichVu> _ChiTietDichVus;
		
		private EntitySet<HoaDonDichVu> _HoaDonDichVus;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<Phong> _Phong;
		
		private EntityRef<ThuePhong> _ThuePhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaThueChanging(string value);
    partial void OnmaThueChanged();
    partial void OnmaKhachChanging(string value);
    partial void OnmaKhachChanged();
    partial void OnmaPhongChanging(string value);
    partial void OnmaPhongChanged();
    partial void OnngayVaoChanging(System.DateTime value);
    partial void OnngayVaoChanged();
    partial void OnngayRaChanging(System.DateTime value);
    partial void OnngayRaChanged();
    partial void OngioVaoChanging(System.TimeSpan value);
    partial void OngioVaoChanged();
    partial void OngioRaChanging(System.TimeSpan value);
    partial void OngioRaChanged();
    partial void OntrangThaiChanging(byte value);
    partial void OntrangThaiChanged();
    partial void OntienKhacChanging(System.Nullable<decimal> value);
    partial void OntienKhacChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public ChiTietThuePhong()
		{
			this._ChiTietDichVus = new EntitySet<ChiTietDichVu>(new Action<ChiTietDichVu>(this.attach_ChiTietDichVus), new Action<ChiTietDichVu>(this.detach_ChiTietDichVus));
			this._HoaDonDichVus = new EntitySet<HoaDonDichVu>(new Action<HoaDonDichVu>(this.attach_HoaDonDichVus), new Action<HoaDonDichVu>(this.detach_HoaDonDichVus));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._Phong = default(EntityRef<Phong>);
			this._ThuePhong = default(EntityRef<ThuePhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThue", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThue
		{
			get
			{
				return this._maThue;
			}
			set
			{
				if ((this._maThue != value))
				{
					if (this._ThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaThueChanging(value);
					this.SendPropertyChanging();
					this._maThue = value;
					this.SendPropertyChanged("maThue");
					this.OnmaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhach", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhach
		{
			get
			{
				return this._maKhach;
			}
			set
			{
				if ((this._maKhach != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachChanging(value);
					this.SendPropertyChanging();
					this._maKhach = value;
					this.SendPropertyChanged("maKhach");
					this.OnmaKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhong", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhong
		{
			get
			{
				return this._maPhong;
			}
			set
			{
				if ((this._maPhong != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongChanging(value);
					this.SendPropertyChanging();
					this._maPhong = value;
					this.SendPropertyChanged("maPhong");
					this.OnmaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayVao", DbType="DateTime NOT NULL")]
		public System.DateTime ngayVao
		{
			get
			{
				return this._ngayVao;
			}
			set
			{
				if ((this._ngayVao != value))
				{
					this.OnngayVaoChanging(value);
					this.SendPropertyChanging();
					this._ngayVao = value;
					this.SendPropertyChanged("ngayVao");
					this.OnngayVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayRa", DbType="DateTime NOT NULL")]
		public System.DateTime ngayRa
		{
			get
			{
				return this._ngayRa;
			}
			set
			{
				if ((this._ngayRa != value))
				{
					this.OnngayRaChanging(value);
					this.SendPropertyChanging();
					this._ngayRa = value;
					this.SendPropertyChanged("ngayRa");
					this.OnngayRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioVao", DbType="Time NOT NULL")]
		public System.TimeSpan gioVao
		{
			get
			{
				return this._gioVao;
			}
			set
			{
				if ((this._gioVao != value))
				{
					this.OngioVaoChanging(value);
					this.SendPropertyChanging();
					this._gioVao = value;
					this.SendPropertyChanged("gioVao");
					this.OngioVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioRa", DbType="Time NOT NULL")]
		public System.TimeSpan gioRa
		{
			get
			{
				return this._gioRa;
			}
			set
			{
				if ((this._gioRa != value))
				{
					this.OngioRaChanging(value);
					this.SendPropertyChanging();
					this._gioRa = value;
					this.SendPropertyChanged("gioRa");
					this.OngioRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="TinyInt NOT NULL")]
		public byte trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienKhac", DbType="Money")]
		public System.Nullable<decimal> tienKhac
		{
			get
			{
				return this._tienKhac;
			}
			set
			{
				if ((this._tienKhac != value))
				{
					this.OntienKhacChanging(value);
					this.SendPropertyChanging();
					this._tienKhac = value;
					this.SendPropertyChanged("tienKhac");
					this.OntienKhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(MAX)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietThuePhong_ChiTietDichVu", Storage="_ChiTietDichVus", ThisKey="maThue,maKhach,maPhong", OtherKey="maThue,maKhach,maPhong")]
		public EntitySet<ChiTietDichVu> ChiTietDichVus
		{
			get
			{
				return this._ChiTietDichVus;
			}
			set
			{
				this._ChiTietDichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietThuePhong_HoaDonDichVu", Storage="_HoaDonDichVus", ThisKey="maThue,maKhach,maPhong", OtherKey="maThue,maKhach,maPhong")]
		public EntitySet<HoaDonDichVu> HoaDonDichVus
		{
			get
			{
				return this._HoaDonDichVus;
			}
			set
			{
				this._HoaDonDichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ChiTietThuePhong", Storage="_KhachHang", ThisKey="maKhach", OtherKey="maKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.ChiTietThuePhongs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietThuePhongs.Add(this);
						this._maKhach = value.maKH;
					}
					else
					{
						this._maKhach = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_ChiTietThuePhong", Storage="_Phong", ThisKey="maPhong", OtherKey="maPhong", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.ChiTietThuePhongs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.ChiTietThuePhongs.Add(this);
						this._maPhong = value.maPhong;
					}
					else
					{
						this._maPhong = default(string);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuePhong_ChiTietThuePhong", Storage="_ThuePhong", ThisKey="maThue", OtherKey="maThue", IsForeignKey=true)]
		public ThuePhong ThuePhong
		{
			get
			{
				return this._ThuePhong.Entity;
			}
			set
			{
				ThuePhong previousValue = this._ThuePhong.Entity;
				if (((previousValue != value) 
							|| (this._ThuePhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThuePhong.Entity = null;
						previousValue.ChiTietThuePhongs.Remove(this);
					}
					this._ThuePhong.Entity = value;
					if ((value != null))
					{
						value.ChiTietThuePhongs.Add(this);
						this._maThue = value.maThue;
					}
					else
					{
						this._maThue = default(string);
					}
					this.SendPropertyChanged("ThuePhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDichVus(ChiTietDichVu entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietThuePhong = this;
		}
		
		private void detach_ChiTietDichVus(ChiTietDichVu entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietThuePhong = null;
		}
		
		private void attach_HoaDonDichVus(HoaDonDichVu entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietThuePhong = this;
		}
		
		private void detach_HoaDonDichVus(HoaDonDichVu entity)
		{
			this.SendPropertyChanging();
			entity.ChiTietThuePhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDV;
		
		private string _tenDichVu;
		
		private System.Nullable<decimal> _donGia;
		
		private System.Nullable<int> _soLuongDV;
		
		private EntitySet<ChiTietDichVu> _ChiTietDichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDVChanging(string value);
    partial void OnmaDVChanged();
    partial void OntenDichVuChanging(string value);
    partial void OntenDichVuChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    partial void OnsoLuongDVChanging(System.Nullable<int> value);
    partial void OnsoLuongDVChanged();
    #endregion
		
		public DichVu()
		{
			this._ChiTietDichVus = new EntitySet<ChiTietDichVu>(new Action<ChiTietDichVu>(this.attach_ChiTietDichVus), new Action<ChiTietDichVu>(this.detach_ChiTietDichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDV", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDV
		{
			get
			{
				return this._maDV;
			}
			set
			{
				if ((this._maDV != value))
				{
					this.OnmaDVChanging(value);
					this.SendPropertyChanging();
					this._maDV = value;
					this.SendPropertyChanged("maDV");
					this.OnmaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDichVu", DbType="NVarChar(50)")]
		public string tenDichVu
		{
			get
			{
				return this._tenDichVu;
			}
			set
			{
				if ((this._tenDichVu != value))
				{
					this.OntenDichVuChanging(value);
					this.SendPropertyChanging();
					this._tenDichVu = value;
					this.SendPropertyChanged("tenDichVu");
					this.OntenDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Money")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongDV", DbType="Int")]
		public System.Nullable<int> soLuongDV
		{
			get
			{
				return this._soLuongDV;
			}
			set
			{
				if ((this._soLuongDV != value))
				{
					this.OnsoLuongDVChanging(value);
					this.SendPropertyChanging();
					this._soLuongDV = value;
					this.SendPropertyChanged("soLuongDV");
					this.OnsoLuongDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_ChiTietDichVu", Storage="_ChiTietDichVus", ThisKey="maDV", OtherKey="maDV")]
		public EntitySet<ChiTietDichVu> ChiTietDichVus
		{
			get
			{
				return this._ChiTietDichVus;
			}
			set
			{
				this._ChiTietDichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDichVus(ChiTietDichVu entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = this;
		}
		
		private void detach_ChiTietDichVus(ChiTietDichVu entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doan")]
	public partial class Doan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDoan;
		
		private string _tenDoan;
		
		private string _soDienThoai;
		
		private string _diaChi;
		
		private string _maTruongDoan;
		
		private EntitySet<ThuePhong> _ThuePhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDoanChanging(string value);
    partial void OnmaDoanChanged();
    partial void OntenDoanChanging(string value);
    partial void OntenDoanChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnmaTruongDoanChanging(string value);
    partial void OnmaTruongDoanChanged();
    #endregion
		
		public Doan()
		{
			this._ThuePhongs = new EntitySet<ThuePhong>(new Action<ThuePhong>(this.attach_ThuePhongs), new Action<ThuePhong>(this.detach_ThuePhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDoan", DbType="NVarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDoan
		{
			get
			{
				return this._maDoan;
			}
			set
			{
				if ((this._maDoan != value))
				{
					this.OnmaDoanChanging(value);
					this.SendPropertyChanging();
					this._maDoan = value;
					this.SendPropertyChanged("maDoan");
					this.OnmaDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenDoan
		{
			get
			{
				return this._tenDoan;
			}
			set
			{
				if ((this._tenDoan != value))
				{
					this.OntenDoanChanging(value);
					this.SendPropertyChanging();
					this._tenDoan = value;
					this.SendPropertyChanged("tenDoan");
					this.OntenDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(11)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTruongDoan", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string maTruongDoan
		{
			get
			{
				return this._maTruongDoan;
			}
			set
			{
				if ((this._maTruongDoan != value))
				{
					this.OnmaTruongDoanChanging(value);
					this.SendPropertyChanging();
					this._maTruongDoan = value;
					this.SendPropertyChanged("maTruongDoan");
					this.OnmaTruongDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doan_ThuePhong", Storage="_ThuePhongs", ThisKey="maDoan", OtherKey="maDoan")]
		public EntitySet<ThuePhong> ThuePhongs
		{
			get
			{
				return this._ThuePhongs;
			}
			set
			{
				this._ThuePhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Doan = this;
		}
		
		private void detach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Doan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonDichVu")]
	public partial class HoaDonDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDDV;
		
		private string _maThue;
		
		private string _maPhong;
		
		private string _maKhach;
		
		private System.DateTime _ngayLap;
		
		private System.TimeSpan _gioLap;
		
		private EntityRef<ChiTietThuePhong> _ChiTietThuePhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDDVChanging(string value);
    partial void OnmaHDDVChanged();
    partial void OnmaThueChanging(string value);
    partial void OnmaThueChanged();
    partial void OnmaPhongChanging(string value);
    partial void OnmaPhongChanged();
    partial void OnmaKhachChanging(string value);
    partial void OnmaKhachChanged();
    partial void OnngayLapChanging(System.DateTime value);
    partial void OnngayLapChanged();
    partial void OngioLapChanging(System.TimeSpan value);
    partial void OngioLapChanged();
    #endregion
		
		public HoaDonDichVu()
		{
			this._ChiTietThuePhong = default(EntityRef<ChiTietThuePhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDDV", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDDV
		{
			get
			{
				return this._maHDDV;
			}
			set
			{
				if ((this._maHDDV != value))
				{
					this.OnmaHDDVChanging(value);
					this.SendPropertyChanging();
					this._maHDDV = value;
					this.SendPropertyChanged("maHDDV");
					this.OnmaHDDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThue", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string maThue
		{
			get
			{
				return this._maThue;
			}
			set
			{
				if ((this._maThue != value))
				{
					if (this._ChiTietThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaThueChanging(value);
					this.SendPropertyChanging();
					this._maThue = value;
					this.SendPropertyChanged("maThue");
					this.OnmaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhong", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string maPhong
		{
			get
			{
				return this._maPhong;
			}
			set
			{
				if ((this._maPhong != value))
				{
					if (this._ChiTietThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongChanging(value);
					this.SendPropertyChanging();
					this._maPhong = value;
					this.SendPropertyChanged("maPhong");
					this.OnmaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhach", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string maKhach
		{
			get
			{
				return this._maKhach;
			}
			set
			{
				if ((this._maKhach != value))
				{
					if (this._ChiTietThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachChanging(value);
					this.SendPropertyChanging();
					this._maKhach = value;
					this.SendPropertyChanged("maKhach");
					this.OnmaKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime NOT NULL")]
		public System.DateTime ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioLap", DbType="Time NOT NULL")]
		public System.TimeSpan gioLap
		{
			get
			{
				return this._gioLap;
			}
			set
			{
				if ((this._gioLap != value))
				{
					this.OngioLapChanging(value);
					this.SendPropertyChanging();
					this._gioLap = value;
					this.SendPropertyChanged("gioLap");
					this.OngioLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiTietThuePhong_HoaDonDichVu", Storage="_ChiTietThuePhong", ThisKey="maThue,maKhach,maPhong", OtherKey="maThue,maKhach,maPhong", IsForeignKey=true)]
		public ChiTietThuePhong ChiTietThuePhong
		{
			get
			{
				return this._ChiTietThuePhong.Entity;
			}
			set
			{
				ChiTietThuePhong previousValue = this._ChiTietThuePhong.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietThuePhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietThuePhong.Entity = null;
						previousValue.HoaDonDichVus.Remove(this);
					}
					this._ChiTietThuePhong.Entity = value;
					if ((value != null))
					{
						value.HoaDonDichVus.Add(this);
						this._maThue = value.maThue;
						this._maKhach = value.maKhach;
						this._maPhong = value.maPhong;
					}
					else
					{
						this._maThue = default(string);
						this._maKhach = default(string);
						this._maPhong = default(string);
					}
					this.SendPropertyChanged("ChiTietThuePhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonTienPhong")]
	public partial class HoaDonTienPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHDPhong;
		
		private string _maThue;
		
		private System.DateTime _ngayLap;
		
		private System.TimeSpan _gioLap;
		
		private double _thueVAT;
		
		private System.Nullable<double> _khuyenMai;
		
		private string _ghiChu;
		
		private EntityRef<ThuePhong> _ThuePhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDPhongChanging(string value);
    partial void OnmaHDPhongChanged();
    partial void OnmaThueChanging(string value);
    partial void OnmaThueChanged();
    partial void OnngayLapChanging(System.DateTime value);
    partial void OnngayLapChanged();
    partial void OngioLapChanging(System.TimeSpan value);
    partial void OngioLapChanged();
    partial void OnthueVATChanging(double value);
    partial void OnthueVATChanged();
    partial void OnkhuyenMaiChanging(System.Nullable<double> value);
    partial void OnkhuyenMaiChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public HoaDonTienPhong()
		{
			this._ThuePhong = default(EntityRef<ThuePhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHDPhong", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHDPhong
		{
			get
			{
				return this._maHDPhong;
			}
			set
			{
				if ((this._maHDPhong != value))
				{
					this.OnmaHDPhongChanging(value);
					this.SendPropertyChanging();
					this._maHDPhong = value;
					this.SendPropertyChanged("maHDPhong");
					this.OnmaHDPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThue", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string maThue
		{
			get
			{
				return this._maThue;
			}
			set
			{
				if ((this._maThue != value))
				{
					if (this._ThuePhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaThueChanging(value);
					this.SendPropertyChanging();
					this._maThue = value;
					this.SendPropertyChanged("maThue");
					this.OnmaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="DateTime NOT NULL")]
		public System.DateTime ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioLap", DbType="Time NOT NULL")]
		public System.TimeSpan gioLap
		{
			get
			{
				return this._gioLap;
			}
			set
			{
				if ((this._gioLap != value))
				{
					this.OngioLapChanging(value);
					this.SendPropertyChanging();
					this._gioLap = value;
					this.SendPropertyChanged("gioLap");
					this.OngioLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thueVAT", DbType="Float NOT NULL")]
		public double thueVAT
		{
			get
			{
				return this._thueVAT;
			}
			set
			{
				if ((this._thueVAT != value))
				{
					this.OnthueVATChanging(value);
					this.SendPropertyChanging();
					this._thueVAT = value;
					this.SendPropertyChanged("thueVAT");
					this.OnthueVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuyenMai", DbType="Float")]
		public System.Nullable<double> khuyenMai
		{
			get
			{
				return this._khuyenMai;
			}
			set
			{
				if ((this._khuyenMai != value))
				{
					this.OnkhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._khuyenMai = value;
					this.SendPropertyChanged("khuyenMai");
					this.OnkhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(100)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuePhong_HoaDonTienPhong", Storage="_ThuePhong", ThisKey="maThue", OtherKey="maThue", IsForeignKey=true)]
		public ThuePhong ThuePhong
		{
			get
			{
				return this._ThuePhong.Entity;
			}
			set
			{
				ThuePhong previousValue = this._ThuePhong.Entity;
				if (((previousValue != value) 
							|| (this._ThuePhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThuePhong.Entity = null;
						previousValue.HoaDonTienPhongs.Remove(this);
					}
					this._ThuePhong.Entity = value;
					if ((value != null))
					{
						value.HoaDonTienPhongs.Add(this);
						this._maThue = value.maThue;
					}
					else
					{
						this._maThue = default(string);
					}
					this.SendPropertyChanged("ThuePhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _tenKh;
		
		private string _soCMND;
		
		private byte _gioiTinh;
		
		private string _soDT;
		
		private EntitySet<ChiTietThuePhong> _ChiTietThuePhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OntenKhChanging(string value);
    partial void OntenKhChanged();
    partial void OnsoCMNDChanging(string value);
    partial void OnsoCMNDChanged();
    partial void OngioiTinhChanging(byte value);
    partial void OngioiTinhChanged();
    partial void OnsoDTChanging(string value);
    partial void OnsoDTChanged();
    #endregion
		
		public KhachHang()
		{
			this._ChiTietThuePhongs = new EntitySet<ChiTietThuePhong>(new Action<ChiTietThuePhong>(this.attach_ChiTietThuePhongs), new Action<ChiTietThuePhong>(this.detach_ChiTietThuePhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenKh
		{
			get
			{
				return this._tenKh;
			}
			set
			{
				if ((this._tenKh != value))
				{
					this.OntenKhChanging(value);
					this.SendPropertyChanging();
					this._tenKh = value;
					this.SendPropertyChanged("tenKh");
					this.OntenKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCMND", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string soCMND
		{
			get
			{
				return this._soCMND;
			}
			set
			{
				if ((this._soCMND != value))
				{
					this.OnsoCMNDChanging(value);
					this.SendPropertyChanging();
					this._soCMND = value;
					this.SendPropertyChanged("soCMND");
					this.OnsoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="TinyInt NOT NULL")]
		public byte gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDT", DbType="NChar(11)")]
		public string soDT
		{
			get
			{
				return this._soDT;
			}
			set
			{
				if ((this._soDT != value))
				{
					this.OnsoDTChanging(value);
					this.SendPropertyChanging();
					this._soDT = value;
					this.SendPropertyChanged("soDT");
					this.OnsoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_ChiTietThuePhong", Storage="_ChiTietThuePhongs", ThisKey="maKH", OtherKey="maKhach")]
		public EntitySet<ChiTietThuePhong> ChiTietThuePhongs
		{
			get
			{
				return this._ChiTietThuePhongs;
			}
			set
			{
				this._ChiTietThuePhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiPhong")]
	public partial class LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoaiPhong;
		
		private string _tenLoaiPhong;
		
		private System.Nullable<decimal> _donGia;
		
		private System.Nullable<int> _soNguoiToiDa;
		
		private EntitySet<Phong> _Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiPhongChanging(string value);
    partial void OnmaLoaiPhongChanged();
    partial void OntenLoaiPhongChanging(string value);
    partial void OntenLoaiPhongChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    partial void OnsoNguoiToiDaChanging(System.Nullable<int> value);
    partial void OnsoNguoiToiDaChanged();
    #endregion
		
		public LoaiPhong()
		{
			this._Phongs = new EntitySet<Phong>(new Action<Phong>(this.attach_Phongs), new Action<Phong>(this.detach_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiPhong", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoaiPhong
		{
			get
			{
				return this._maLoaiPhong;
			}
			set
			{
				if ((this._maLoaiPhong != value))
				{
					this.OnmaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._maLoaiPhong = value;
					this.SendPropertyChanged("maLoaiPhong");
					this.OnmaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoaiPhong", DbType="NVarChar(50)")]
		public string tenLoaiPhong
		{
			get
			{
				return this._tenLoaiPhong;
			}
			set
			{
				if ((this._tenLoaiPhong != value))
				{
					this.OntenLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._tenLoaiPhong = value;
					this.SendPropertyChanged("tenLoaiPhong");
					this.OntenLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Money")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNguoiToiDa", DbType="Int")]
		public System.Nullable<int> soNguoiToiDa
		{
			get
			{
				return this._soNguoiToiDa;
			}
			set
			{
				if ((this._soNguoiToiDa != value))
				{
					this.OnsoNguoiToiDaChanging(value);
					this.SendPropertyChanging();
					this._soNguoiToiDa = value;
					this.SendPropertyChanged("soNguoiToiDa");
					this.OnsoNguoiToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_Phongs", ThisKey="maLoaiPhong", OtherKey="maLoaiPhong")]
		public EntitySet<Phong> Phongs
		{
			get
			{
				return this._Phongs;
			}
			set
			{
				this._Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = this;
		}
		
		private void detach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _tenNV;
		
		private string _soCMND;
		
		private byte _gioiTinh;
		
		private System.DateTime _ngaySinh;
		
		private string _soDT;
		
		private byte _chucVu;
		
		private string _passWord;
		
		private string _email;
		
		private EntitySet<ThuePhong> _ThuePhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OntenNVChanging(string value);
    partial void OntenNVChanged();
    partial void OnsoCMNDChanging(string value);
    partial void OnsoCMNDChanged();
    partial void OngioiTinhChanging(byte value);
    partial void OngioiTinhChanged();
    partial void OnngaySinhChanging(System.DateTime value);
    partial void OnngaySinhChanged();
    partial void OnsoDTChanging(string value);
    partial void OnsoDTChanged();
    partial void OnchucVuChanging(byte value);
    partial void OnchucVuChanged();
    partial void OnpassWordChanging(string value);
    partial void OnpassWordChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public NhanVien()
		{
			this._ThuePhongs = new EntitySet<ThuePhong>(new Action<ThuePhong>(this.attach_ThuePhongs), new Action<ThuePhong>(this.detach_ThuePhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenNV
		{
			get
			{
				return this._tenNV;
			}
			set
			{
				if ((this._tenNV != value))
				{
					this.OntenNVChanging(value);
					this.SendPropertyChanging();
					this._tenNV = value;
					this.SendPropertyChanged("tenNV");
					this.OntenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCMND", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string soCMND
		{
			get
			{
				return this._soCMND;
			}
			set
			{
				if ((this._soCMND != value))
				{
					this.OnsoCMNDChanging(value);
					this.SendPropertyChanging();
					this._soCMND = value;
					this.SendPropertyChanged("soCMND");
					this.OnsoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="TinyInt NOT NULL")]
		public byte gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDT", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string soDT
		{
			get
			{
				return this._soDT;
			}
			set
			{
				if ((this._soDT != value))
				{
					this.OnsoDTChanging(value);
					this.SendPropertyChanging();
					this._soDT = value;
					this.SendPropertyChanged("soDT");
					this.OnsoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucVu", DbType="TinyInt NOT NULL")]
		public byte chucVu
		{
			get
			{
				return this._chucVu;
			}
			set
			{
				if ((this._chucVu != value))
				{
					this.OnchucVuChanging(value);
					this.SendPropertyChanging();
					this._chucVu = value;
					this.SendPropertyChanged("chucVu");
					this.OnchucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passWord", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string passWord
		{
			get
			{
				return this._passWord;
			}
			set
			{
				if ((this._passWord != value))
				{
					this.OnpassWordChanging(value);
					this.SendPropertyChanging();
					this._passWord = value;
					this.SendPropertyChanged("passWord");
					this.OnpassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThuePhong", Storage="_ThuePhongs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<ThuePhong> ThuePhongs
		{
			get
			{
				return this._ThuePhongs;
			}
			set
			{
				this._ThuePhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhong;
		
		private string _maLoaiPhong;
		
		private string _tenPhong;
		
		private int _tang;
		
		private bool _tinhTrang;
		
		private string _ghiChu;
		
		private System.Nullable<int> _soNguoiHienTai;
		
		private EntitySet<ChiTietThuePhong> _ChiTietThuePhongs;
		
		private EntityRef<LoaiPhong> _LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhongChanging(string value);
    partial void OnmaPhongChanged();
    partial void OnmaLoaiPhongChanging(string value);
    partial void OnmaLoaiPhongChanged();
    partial void OntenPhongChanging(string value);
    partial void OntenPhongChanged();
    partial void OntangChanging(int value);
    partial void OntangChanged();
    partial void OntinhTrangChanging(bool value);
    partial void OntinhTrangChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnsoNguoiHienTaiChanging(System.Nullable<int> value);
    partial void OnsoNguoiHienTaiChanged();
    #endregion
		
		public Phong()
		{
			this._ChiTietThuePhongs = new EntitySet<ChiTietThuePhong>(new Action<ChiTietThuePhong>(this.attach_ChiTietThuePhongs), new Action<ChiTietThuePhong>(this.detach_ChiTietThuePhongs));
			this._LoaiPhong = default(EntityRef<LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhong", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhong
		{
			get
			{
				return this._maPhong;
			}
			set
			{
				if ((this._maPhong != value))
				{
					this.OnmaPhongChanging(value);
					this.SendPropertyChanging();
					this._maPhong = value;
					this.SendPropertyChanged("maPhong");
					this.OnmaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiPhong", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string maLoaiPhong
		{
			get
			{
				return this._maLoaiPhong;
			}
			set
			{
				if ((this._maLoaiPhong != value))
				{
					if (this._LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._maLoaiPhong = value;
					this.SendPropertyChanged("maLoaiPhong");
					this.OnmaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenPhong
		{
			get
			{
				return this._tenPhong;
			}
			set
			{
				if ((this._tenPhong != value))
				{
					this.OntenPhongChanging(value);
					this.SendPropertyChanging();
					this._tenPhong = value;
					this.SendPropertyChanged("tenPhong");
					this.OntenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tang", DbType="Int NOT NULL")]
		public int tang
		{
			get
			{
				return this._tang;
			}
			set
			{
				if ((this._tang != value))
				{
					this.OntangChanging(value);
					this.SendPropertyChanging();
					this._tang = value;
					this.SendPropertyChanged("tang");
					this.OntangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrang", DbType="Bit NOT NULL")]
		public bool tinhTrang
		{
			get
			{
				return this._tinhTrang;
			}
			set
			{
				if ((this._tinhTrang != value))
				{
					this.OntinhTrangChanging(value);
					this.SendPropertyChanging();
					this._tinhTrang = value;
					this.SendPropertyChanged("tinhTrang");
					this.OntinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(50)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNguoiHienTai", DbType="Int")]
		public System.Nullable<int> soNguoiHienTai
		{
			get
			{
				return this._soNguoiHienTai;
			}
			set
			{
				if ((this._soNguoiHienTai != value))
				{
					this.OnsoNguoiHienTaiChanging(value);
					this.SendPropertyChanging();
					this._soNguoiHienTai = value;
					this.SendPropertyChanged("soNguoiHienTai");
					this.OnsoNguoiHienTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_ChiTietThuePhong", Storage="_ChiTietThuePhongs", ThisKey="maPhong", OtherKey="maPhong")]
		public EntitySet<ChiTietThuePhong> ChiTietThuePhongs
		{
			get
			{
				return this._ChiTietThuePhongs;
			}
			set
			{
				this._ChiTietThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_LoaiPhong", ThisKey="maLoaiPhong", OtherKey="maLoaiPhong", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LoaiPhong LoaiPhong
		{
			get
			{
				return this._LoaiPhong.Entity;
			}
			set
			{
				LoaiPhong previousValue = this._LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiPhong.Entity = null;
						previousValue.Phongs.Remove(this);
					}
					this._LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.Phongs.Add(this);
						this._maLoaiPhong = value.maLoaiPhong;
					}
					else
					{
						this._maLoaiPhong = default(string);
					}
					this.SendPropertyChanged("LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuePhong")]
	public partial class ThuePhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maThue;
		
		private string _maNV;
		
		private int _soLuongPhong;
		
		private string _maDoan;
		
		private byte _trangThai;
		
		private EntitySet<ChiTietThuePhong> _ChiTietThuePhongs;
		
		private EntitySet<HoaDonTienPhong> _HoaDonTienPhongs;
		
		private EntityRef<Doan> _Doan;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaThueChanging(string value);
    partial void OnmaThueChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnsoLuongPhongChanging(int value);
    partial void OnsoLuongPhongChanged();
    partial void OnmaDoanChanging(string value);
    partial void OnmaDoanChanged();
    partial void OntrangThaiChanging(byte value);
    partial void OntrangThaiChanged();
    #endregion
		
		public ThuePhong()
		{
			this._ChiTietThuePhongs = new EntitySet<ChiTietThuePhong>(new Action<ChiTietThuePhong>(this.attach_ChiTietThuePhongs), new Action<ChiTietThuePhong>(this.detach_ChiTietThuePhongs));
			this._HoaDonTienPhongs = new EntitySet<HoaDonTienPhong>(new Action<HoaDonTienPhong>(this.attach_HoaDonTienPhongs), new Action<HoaDonTienPhong>(this.detach_HoaDonTienPhongs));
			this._Doan = default(EntityRef<Doan>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThue", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThue
		{
			get
			{
				return this._maThue;
			}
			set
			{
				if ((this._maThue != value))
				{
					this.OnmaThueChanging(value);
					this.SendPropertyChanging();
					this._maThue = value;
					this.SendPropertyChanged("maThue");
					this.OnmaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongPhong", DbType="Int NOT NULL")]
		public int soLuongPhong
		{
			get
			{
				return this._soLuongPhong;
			}
			set
			{
				if ((this._soLuongPhong != value))
				{
					this.OnsoLuongPhongChanging(value);
					this.SendPropertyChanging();
					this._soLuongPhong = value;
					this.SendPropertyChanged("soLuongPhong");
					this.OnsoLuongPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDoan", DbType="NVarChar(7)")]
		public string maDoan
		{
			get
			{
				return this._maDoan;
			}
			set
			{
				if ((this._maDoan != value))
				{
					if (this._Doan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDoanChanging(value);
					this.SendPropertyChanging();
					this._maDoan = value;
					this.SendPropertyChanged("maDoan");
					this.OnmaDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="TinyInt NOT NULL")]
		public byte trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuePhong_ChiTietThuePhong", Storage="_ChiTietThuePhongs", ThisKey="maThue", OtherKey="maThue")]
		public EntitySet<ChiTietThuePhong> ChiTietThuePhongs
		{
			get
			{
				return this._ChiTietThuePhongs;
			}
			set
			{
				this._ChiTietThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuePhong_HoaDonTienPhong", Storage="_HoaDonTienPhongs", ThisKey="maThue", OtherKey="maThue")]
		public EntitySet<HoaDonTienPhong> HoaDonTienPhongs
		{
			get
			{
				return this._HoaDonTienPhongs;
			}
			set
			{
				this._HoaDonTienPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doan_ThuePhong", Storage="_Doan", ThisKey="maDoan", OtherKey="maDoan", IsForeignKey=true)]
		public Doan Doan
		{
			get
			{
				return this._Doan.Entity;
			}
			set
			{
				Doan previousValue = this._Doan.Entity;
				if (((previousValue != value) 
							|| (this._Doan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Doan.Entity = null;
						previousValue.ThuePhongs.Remove(this);
					}
					this._Doan.Entity = value;
					if ((value != null))
					{
						value.ThuePhongs.Add(this);
						this._maDoan = value.maDoan;
					}
					else
					{
						this._maDoan = default(string);
					}
					this.SendPropertyChanged("Doan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ThuePhong", Storage="_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ThuePhongs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ThuePhongs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.ThuePhong = this;
		}
		
		private void detach_ChiTietThuePhongs(ChiTietThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.ThuePhong = null;
		}
		
		private void attach_HoaDonTienPhongs(HoaDonTienPhong entity)
		{
			this.SendPropertyChanging();
			entity.ThuePhong = this;
		}
		
		private void detach_HoaDonTienPhongs(HoaDonTienPhong entity)
		{
			this.SendPropertyChanging();
			entity.ThuePhong = null;
		}
	}
}
#pragma warning restore 1591
