<?xml version="1.0" encoding="utf-8"?><Database Name="KhachSan" Class="dbQLKhachSanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=THANHQUY\SQLEXPRESS;Initial Catalog=KhachSan;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="KhachSanConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietDichVu" Member="ChiTietDichVus">
    <Type Name="ChiTietDichVu">
      <Column Name="maThue" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKhach" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maPhong" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDV" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ChiTietThuePhong_ChiTietDichVu" Member="ChiTietThuePhong" ThisKey="maThue,maKhach,maPhong" OtherKey="maThue,maKhach,maPhong" Type="ChiTietThuePhong" IsForeignKey="true" />
      <Association Name="DichVu_ChiTietDichVu" Member="DichVu" ThisKey="maDV" OtherKey="maDV" Type="DichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietThuePhong" Member="ChiTietThuePhongs">
    <Type Name="ChiTietThuePhong">
      <Column Name="maThue" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKhach" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maPhong" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayVao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngayRa" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="gioVao" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="gioRa" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="tienKhac" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ChiTietThuePhong_ChiTietDichVu" Member="ChiTietDichVus" ThisKey="maThue,maKhach,maPhong" OtherKey="maThue,maKhach,maPhong" Type="ChiTietDichVu" />
      <Association Name="ChiTietThuePhong_HoaDonDichVu" Member="HoaDonDichVus" ThisKey="maThue,maKhach,maPhong" OtherKey="maThue,maKhach,maPhong" Type="HoaDonDichVu" />
      <Association Name="KhachHang_ChiTietThuePhong" Member="KhachHang" ThisKey="maKhach" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="Phong_ChiTietThuePhong" Member="Phong" ThisKey="maPhong" OtherKey="maPhong" Type="Phong" IsForeignKey="true" />
      <Association Name="ThuePhong_ChiTietThuePhong" Member="ThuePhong" ThisKey="maThue" OtherKey="maThue" Type="ThuePhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="maDV" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenDichVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="soLuongDV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DichVu_ChiTietDichVu" Member="ChiTietDichVus" ThisKey="maDV" OtherKey="maDV" Type="ChiTietDichVu" />
    </Type>
  </Table>
  <Table Name="dbo.Doan" Member="Doans">
    <Type Name="Doan">
      <Column Name="maDoan" Type="System.String" DbType="NVarChar(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenDoan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soDienThoai" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="maTruongDoan" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Association Name="Doan_ThuePhong" Member="ThuePhongs" ThisKey="maDoan" OtherKey="maDoan" Type="ThuePhong" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonDichVu" Member="HoaDonDichVus">
    <Type Name="HoaDonDichVu">
      <Column Name="maHDDV" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maThue" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="maPhong" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="maKhach" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="gioLap" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Association Name="ChiTietThuePhong_HoaDonDichVu" Member="ChiTietThuePhong" ThisKey="maThue,maKhach,maPhong" OtherKey="maThue,maKhach,maPhong" Type="ChiTietThuePhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonTienPhong" Member="HoaDonTienPhongs">
    <Type Name="HoaDonTienPhong">
      <Column Name="maHDPhong" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maThue" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="gioLap" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="thueVAT" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="khuyenMai" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ThuePhong_HoaDonTienPhong" Member="ThuePhong" ThisKey="maThue" OtherKey="maThue" Type="ThuePhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="maKH" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soCMND" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="soDT" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Association Name="KhachHang_ChiTietThuePhong" Member="ChiTietThuePhongs" ThisKey="maKH" OtherKey="maKhach" Type="ChiTietThuePhong" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="maLoaiPhong" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenLoaiPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="donGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="soNguoiToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="maLoaiPhong" OtherKey="maLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNV" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soCMND" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="gioiTinh" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="soDT" Type="System.String" DbType="NChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="chucVu" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="passWord" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_ThuePhong" Member="ThuePhongs" ThisKey="maNV" OtherKey="maNV" Type="ThuePhong" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="maPhong" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLoaiPhong" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="tenPhong" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soNguoiHienTai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phong_ChiTietThuePhong" Member="ChiTietThuePhongs" ThisKey="maPhong" OtherKey="maPhong" Type="ChiTietThuePhong" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="maLoaiPhong" OtherKey="maLoaiPhong" Type="LoaiPhong" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuePhong" Member="ThuePhongs">
    <Type Name="ThuePhong">
      <Column Name="maThue" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="soLuongPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maDoan" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="ThuePhong_ChiTietThuePhong" Member="ChiTietThuePhongs" ThisKey="maThue" OtherKey="maThue" Type="ChiTietThuePhong" />
      <Association Name="ThuePhong_HoaDonTienPhong" Member="HoaDonTienPhongs" ThisKey="maThue" OtherKey="maThue" Type="HoaDonTienPhong" />
      <Association Name="Doan_ThuePhong" Member="Doan" ThisKey="maDoan" OtherKey="maDoan" Type="Doan" IsForeignKey="true" />
      <Association Name="NhanVien_ThuePhong" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>